## Question  
**How do you test that a Python function throws an exception?**

## Running the Tests

To run the tests for this project, follow the steps below:

1. **Clone the Repository**  
   Use the following command to clone the repository:

   `git clone https://github.com/Itor-Carlos/Teste_Software_2025_Queiroz_Itor.git`

2. **Navigate to the Project Directory**  
   Open your terminal in the project folder.

3. **Run the Test File**  
   Execute the test script using the following command:

   `python test_usuario.py`
